### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-conditionals-uMDt4P#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-js-conditionals-uMDt4P/) and meets the following criteria:

- [x] Use the `prompt` and `confirm` functions (each at least once) to collect choices from the user (the entire story will take place in dialog boxes, so your `body` element could actually be empty, apart from the `script` element to include your JavaScript)
- [x] Use `if`, `else if`, and `else` to branch the story, based on user choices
- [x] In at least one branch, there should be at least 3 choices for the user to make
- [x] Include at least one branch where different things can happen each time with `Math.random()`
- [x] Use a logical operator (`&&` or `||`) at least once, where it makes sense
- [x] It should be impossible for an error to ever occur when playing your game, including handling for `null`/`undefined` where appropriate
- [x] All string input should be normalized, so that extra whitespace or a letter that's the wrong case will never cause a failed match
- [x] At least one number value is collected and used in a comparison (don't forget to convert it into a number first)
- [x] Don't get _too_ carried away -- it can be tempting to build a complex video game, but remember, you can always come back and build on this project later

**Comment by chrisvfritz** [comment]
So many... 😍 beautiful... 😍 functions! 😍 I'm really impressed by this. 👍 I showed it to Katie and she gave me a high five. That's how much we like it! It can take a while to truly understand the power of functions, but I think you're starting to get it. This is definitely the cleanest project I've seen so far for this lesson - and you even use a function to keep the game going infinitely until the user decides to quit! 😵

But, of course, I do see a couple areas for improvement, plus one stretch goal. 😉 

### `startEntry` accepts string input that isn't normalized

You seem to know how to do this in other places of the program, but let me know if you're not sure what I mean or you need any help. 🙂

### `Uncaught TypeError` when a user refuses to answer (most) trivia questions

When refusing to answer a trivia question with "Cancel", nothing will happen and this error will appear in the browser's JavaScript console:

```
Uncaught TypeError: Cannot read property 'trim' of null
```

Again, let me know if you'd like some guidance in figuring out how to prevent it.

### Try creating a `respondToAnswer` function to respond to any answer

So this has been mentioned before, but won't really be stressed until a subsequent lesson: custom functions can also take _arguments_. For example, here's how we'd create a function that wraps any message with smileys (in case you're afraid it might come across as angry):

``` js
function smileSay (message) {
  alert('😊 ' + message + ' 😊')
}

smileSay('what do you want?')
```

Since right now, you're using the same responses for every question, my challenge for you is to use the function below (replacing the `...` with your own code), to shorten your trivia functions.

``` js
function respondToAnswer (answerWasCorrect) {
  ...
}
```

Of course, let me know if you'd like any help or have any other follow-up questions! 😄 We could even take it a step _further_ after this if you wanted, so you'll have to tell me if you're good - or interested in more function madness. 😜

**Comment by GriffinMartin** [comment]
@chrisvfritz 
Thanks for the feedback! 
I'm confused on two parts here.
For `startEntry` it has `.trim().toLowerCase()`. Is there something else I'm missing, I can't seem to find what I did differently in other spots of the program.
For `Uncaught TypeError: Cannot read property 'trim' of null` I'm confused about the best way to go about this. I have some ideas that would probably work, however they seem cumbersome. 
Thanks! 😄

**Comment by chrisvfritz** [comment]
> For `startEntry` it has `.trim().toLowerCase()`. Is there something else I'm missing, I can't seem to find what I did differently in other spots of the program.

Huh, it looks good to me as well. Not sure how I missed it before. 😅  Sorry about that.

> For `Uncaught TypeError: Cannot read property 'trim' of null` I'm confused about the best way to go about this. I have some ideas that would probably work, however they seem cumbersome.

Tell me about your ideas. 🙂  I'm happy to walk through it with you, either here or on Slack.

> I integrated the `respondToAnswer` function.

This is a little bit different from what I was imagining, but it's also an interesting direction! 🙂 Before your latest commit, each of your trivia functions also included some code like this:

``` js
if (historyAns1 === '1855') {
  correctAns()
  categoryFunc()
} else {
  wrongAns()
  categoryFunc()
}
```

And the only thing that was different was what you were checking: `historyAns1 === '1855'`. So I was imagining a function like this:

``` js
function respondToAnswer (answerWasCorrect) {
  if (answerWasCorrect) {
    correctAns() 
  } else {
    wrongAns()
  }
  // Note that since we always call categoryFunc
  // at the end, I just include it here after the `if`
  // statement has finished
  categoryFunc()
}
```

And _then_, your trivia functions could be shortened to:

``` js
function historyTrivia () {
  var historyAns1 = window.prompt('What year was MSU founded?').trim().toLowerCase()
  respondToAnswer(historyAns1 === '1855')
}
```

Now though, you've added something new! When a user gets something right, the program doesn't always say the same thing. I like that change a lot and I'm wondering if we could take it even further with a 2nd and 3rd parameter to `respondToAnswer`:

``` js
function historyTrivia () {
  var historyAns1 = window.prompt('What year was MSU founded?').trim().toLowerCase()
  respondToAnswer(
    historyAns1 === '1855',
    'Correct, Go Green! ', // the message for correct answers
    'Sorry, the correct answer was 1855. 😕' // the message for wrong answers
  )
}
```

What do you think?

**Comment by GriffinMartin** [comment]
@chrisvfritz 
I updated the respondToAnswer function. Still working on the `Uncaught TypeError: Cannot read property 'trim' of null` error!

**Comment by chrisvfritz** [comment]
_Nice!_ Are you going to develop this into the next big on-campus party game? 😹 🎉 :shipit:
